describe('SEU BARRIGA', function () {
  beforeEach(function () {
    cy.visit('/')
  })
  it('COMEÇO- Verifica o título da aplicação', function () {
    cy.title()
      .should('be.equal', 'Seu Barriga - Log in')
  })
  it('Verifica o Titulo de baixo', function () {
    cy.get('a:contains(Seu Barriga)')
      .should('be.visible')
      .click()
  })
  it('Verifica Campos Obrigatorios', () => {
    cy.get('.btn')
      .click()
    cy.get('.alert')
      .should('be.visible')
    cy.contains('Email é um campo obrigatório')
    cy.contains('Senha é um campo obrigatório')
  })
  it('Valida somente o campo Email', () => {
    cy.get('#email')
      .type('user@user.com')
    cy.get('.btn')
      .click()
    cy.get('.alert')
      .should('be.visible')
    cy.contains('Senha é um campo obrigatório')
  })
  it('Valida somente o campo de Senha', () => {
    cy.get('#senha')
      .type('123')
    cy.get('.btn')
      .click()
    cy.get('.alert')
      .should('be.visible')
    cy.contains('Email é um campo obrigatório')
  })
  it.only('Valica os campos E-mail e Senha', () => {
    cy.get('#email')
    .type('user')
    cy.get('#senha')
    .type('123')
    cy.get('.btn')
    .click()
   })
})