  Cypress.Commands.add('LoginSeuMadruga', function () {
    cy.get('a:contains(Login)')
              .should('be.visible')
              .click()
          cy.get('label:contains(Email)')
              .should('be.visible')
          cy.get('#email')
              .type('user4@user.com')
          cy.get('label:contains(Senha)')
              .should('be.visible')
          cy.get('#senha')
              .type('123')
          cy.contains('.btn', 'Entrar')
              .click()
          cy.get('.alert')
              .should('be.visible')
          cy.contains('.alert', 'Bem vindo, Eduardo2!')
  })    
  