describe('SEU BARRIGA', function () {
    beforeEach(function () {
      cy.visit('/')
    })

it('Verificar campos antes de fazer um novo cadastro', function () {
    cy.get('a:contains(Novo usuário?)')
        .should('be.visible')
        .click()
    cy.get('label:contains(Nome)')
        .should('be.visible')
    cy.get('label:contains(Email)')
        .should('be.visible')
    cy.get('label:contains(Senha)')
        .should('be.visible')
    cy.contains('.btn', 'Cadastrar')
        .should('be.visible')
})
it('Fazer o cadastro', function () {
    cy.get('a:contains(Novo usuário?)')
        .should('be.visible')
        .click()
    cy.get('#nome')
        .type('Eduardo2')
    cy.get('#email')
        .type('user4@user.com')
    cy.get('#senha')
        .type('123')
    cy.contains('.btn', 'Cadastrar')
        .click()
    cy.get('.alert')
        .should('be.visible')
})
})